### ISSUE TITLE
Header Images - allow for every page to have unique header image 

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Serv-A-Yard#30]

**Comment by ccmorris** [comment]
You can already do this with the block settings. Do you have specific ones you want me to set up for you?

**Comment by tgascoigne14** [comment]
All service description pages. When I add a header image to one service description page, I do not want it showing on all description pages. The service category header images need to be customizable as well.

**Comment by ccmorris** [comment]
Like I said, you can already do this. Come see me and I will show you how.
